channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - bioconda::bcftools==1.15.1
  - bioconda::plink2==2.00a3.3
  - conda-forge::matplotlib==3.5.2
  - conda-forge::pandas==1.4.3
  - conda-forge::click==8.1.3
  - conda-forge::numpy==1.23.1
  - conda-forge::seaborn==0.12.0
  - conda-forge::sed==4.8
  - conda-forge::bash==5.0.018
  - conda-forge::gzip==1.10
  - conda-forge::gawk==5.1.0
  - bioconda::haptools==0.1.2
  - bioconda::pysam==0.20.0
